version: '3'
services:
  web:
    build: .
    ports:
      - "${APP_EXTERNAL_PORT}:80"
    volumes:
      - .:/app
  postgres:
    image: "postgres"
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
